name: Build Node Application

on:
    workflow_call:
      inputs:
        proj-path:
          required: true
          type: string


jobs:
    build:
        name: Build Node Api
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run build cmd
              run: |
                echo "Path :: ${{ inputs.proj-path }}" 
                echo "Working Dir : ${{ github.workspace }}" 
                cd ./${{ inputs.proj-path }}
                echo "Working Dir : ${{ github.workspace }}" 
                npm install