name: Build Python Application

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "python/**"
    pull_request:
        branches: [main]
        paths:
            - "python/**"
jobs:
    build:
        name: Build Api
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run build cmd
              run: |
                cd ./python
                pip install -r requirements.txt