name: Build Java Application

on:
    workflow_call:
        inputs:
          proj-path:
            required: true
            type: string

jobs:
    build:
        name: Build Java Api
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '17'

            - name: Run build cmd
              run: |
                cd ./${{ inputs.proj-path}}
                mvn clean install