name: Build Java Application

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "java/**"
    pull_request:
        branches: [main]
        paths:
            - "java/**"
jobs:
    build:
        name: Build Api
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '17'

            - name: Run build cmd
              run: |
                cd ./java
                mvn clean install