name: Read Config

on:
    workflow_call:
      inputs:
        proj-path:
          required: true
          type: string


jobs:
    build:
        name: Read Config
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
           
            - name: Read Config
              id: config
              run: |
                  cd ./${{ inputs.proj-path }}
                  {
                    echo 'CONFIG_JSON<<EOF'
                    cat ./.pipeline/config.json
                    echo 'EOF'
                  } >> $GITHUB_ENV

            - name: Print Value
              run: |
                echo '${{ fromJson(env.CONFIG_JSON) }}'
                echo '${{ fromJson(env.CONFIG_JSON).name }}'

           
            - name: Run build cmd
              run: |
                echo "Path :: ${{ inputs.proj-path }}" 
                echo "Working Dir : ${{ github.workspace }}" 
                cd ./${{ inputs.proj-path}}
                npm install