name: Trigger Build for Application

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-node:
        uses: ./.github/workflows/build-node.yaml