name: Trigger CI Build 

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    changes:
        # if: |
        #   (
        #     (github.event_name == 'push' &&  github.ref_name == 'main') ||
        #     (github.event_name == 'pull_request')
        #   )
        name: Get Changes
        runs-on: ubuntu-latest
        permissions: 
            pull-requests: read
        # Set job outputs to values from filter step
        outputs:
            node: ${{ steps.changes.outputs.node }}
            node2: ${{ steps.changes.outputs.node2 }}
            java: ${{ steps.changes.outputs.java }}
            python: ${{ steps.changes.outputs.python }}
        steps:
            # - name: Checkout repository
            #   uses: actions/checkout@v4
            #   with:
            #     ref: ${{ github.ref }}
            #     fetch-depth: 2

            # - name: Get previous commit SHA
            #   id: prev_commit
            #   run: echo "PREV_COMMIT_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                    node:
                        - 'node/**'
                    node2:
                        - 'node2/**'
                    java:
                        - 'java/**'
                    python:
                        - 'python/**'

    build-node:
        name: Build For Node 
        needs: changes
        if: ${{ needs.changes.outputs.node == 'true' }}
        uses: ./.github/workflows/build-node.yaml
        with:
            proj-path: node

    build-node2:
        name: Build For Node 2
        needs: changes
        if: ${{ needs.changes.outputs.node2 == 'true' }}
        uses: ./.github/workflows/build-node.yaml
        with:
            proj-path: node2
    
    build-java:
        name: Build For Java
        needs: changes
        if: ${{ needs.changes.outputs.java == 'true' }}
        uses: ./.github/workflows/build-java.yaml
        with:
            proj-path: java

    build-python:
        name: Build For Python
        needs: changes
        if: ${{ needs.changes.outputs.python == 'true' }} 
        uses: ./.github/workflows/build-python.yaml
        with:
            proj-path: python